spring:
  application:
    name: WEB-SERVICE
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  servlet:
    session:
      timeout: 15m   # auto logout after 15 minutes inactivity